name: Tests

on: [push, pull_request]
  

jobs:
  buildImage:
    name: Mail server image
    runs-on: ubuntu-22.04
    steps:
    - name: Setup environment
      uses: actions/checkout@master
      
    - name: Cache image
      id: cache-image
      uses: actions/cache@v1
      with:
        path: /tmp/image.tar
        key: ${{ runner.os }}-image-${{ hashFiles('tests/image/**') }}

    - if: ${{ steps.cache-image.outputs.cache-hit != 'true' }}
      name: Install podman
      run: |
        wget http://ftp.us.debian.org/debian/pool/main/libp/libpod/podman_4.2.0+ds1-3_amd64.deb
        sudo dpkg -i podman_4.2.0+ds1-3_amd64.deb
        
      
    - if: ${{ steps.cache-image.outputs.cache-hit != 'true' }}
      name: Build image
      run: |
        podman build --tag mail-memory --output type=tar,dest=/tmp/image.tar tests/image/

    # - name: Upload artifact
      # uses: actions/upload-artifact@v3
      # with:
        # name: tmailImage
        # path: /tmp/image.tar
        # retention-days: 1
        
  test:
    needs: buildImage
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        nim: ['1.6.0', 'stable', 'devel' ]
      fail-fast: false
      max-parallel: 3

    name: Nim ${{ matrix.nim }}
    steps:
    - name: Setup Nim Enviroment
      uses: actions/checkout@master
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ matrix.nim }}-${{ hashFiles('jamp.nimble') }}
    - uses: jiro4989/setup-nim-action@v1
      with:
          nim-version: ${{ matrix.nim }}
          
    - name: Update nimble
      run: nimble update

    - name: Install podman
      run: |
        wget http://ftp.us.debian.org/debian/pool/main/libp/libpod/podman_4.2.0+ds1-3_amd64.deb
        sudo dpkg -i podman_4.2.0+ds1-3_amd64.deb

    # - name: Download artifact
      # uses: actions/download-artifact@v3
      # with:
        # name: tmailImage
        # path: /tmp

    - name: Load image from cache
      id: cache-image
      uses: actions/cache@v1
      with:
        path: /tmp/image.tar
        key: ${{ runner.os }}-image-${{ hashFiles('tests/image/**') }}

    - name: Load image
      run: podman load -i /tmp/image.tar
      
    - name: Start test mail server
      run: nimble startContainer
  
    - name: Run tests
      run: nimble test

    - name: Test doc examples
      run: nimble doc --project src/jamp.nim
