name: Tests

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: ["1.6.0", "stable", "devel"]
      fail-fast: false
      max-parallel: 3

    name: Nim ${{ matrix.nim }}
    steps:
      - name: Setup Nim Enviroment
        uses: actions/checkout@v6

      - name: Install Nim
        uses: iffy/install-nim@v5
        with:
          version: ${{ matrix.nim }}

      - name: Update nimble
        run: nimble update

      - uses: docker/setup-docker-action@v5

      - name: Start test mail server
        run: nimble startContainer

      - name: Run tests
        run: nimble test

      - name: Test doc examples
        run: nimble doc --project src/jamp.nim
